package com.videoshare.interaction;

import com.videoshare.auth.CurrentUser;
import com.videoshare.common.*;
import com.videoshare.video.*;
import java.sql.*;
import java.time.*;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.simple.SimpleJdbcInsert;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class InteractionService {
    private final JdbcTemplate jdbc;private final VideoRepository videos;private final ViewFactory views;private final Map<String,Long> viewDedup=new ConcurrentHashMap<>();
    public InteractionService(JdbcTemplate jdbc,VideoRepository videos,ViewFactory views){this.jdbc=jdbc;this.videos=videos;this.views=views;}
    public Map<String,Object> play(long id,Long viewer){Video v=publicVideo(id);Map<String,Object> m=new LinkedHashMap<>();m.put("hlsUrl",Objects.requireNonNullElse(v.getHlsUrl(),"/demo/hls/master.m3u8"));m.put("qualities",List.of("360p","480p","720p"));m.put("expiresAt",Instant.now().plus(Duration.ofHours(2)));m.put("poster",Objects.requireNonNullElse(v.getCoverUrl(),"/favicon.svg"));return m;}
    public List<Map<String,Object>> related(long id,Long viewer){Video source=publicVideo(id);return videos.findAll().stream().filter(v->!v.getId().equals(id)&&v.getStatus()==VideoStatus.PUBLISHED&&v.getVisibility()==Visibility.PUBLIC).sorted(Comparator.comparing((Video v)->Objects.equals(v.getCategoryId(),source.getCategoryId())).reversed().thenComparing(Video::getViewCount,Comparator.reverseOrder())).limit(12).map(v->views.videoSummary(v,viewer)).toList();}
    @Transactional public Map<String,Object> view(long id,String fingerprint){Video v=publicVideo(id);String key=id+":"+fingerprint;long now=System.currentTimeMillis();Long previous=viewDedup.putIfAbsent(key,now);boolean counted=previous==null||now-previous>86_400_000L;if(counted){viewDedup.put(key,now);v.setCounters(v.getViewCount()+1,v.getLikeCount(),v.getDislikeCount(),v.getCommentCount(),v.getFavoriteCount());}return Map.of("counted",counted,"views",v.getViewCount());}
    @Transactional public Map<String,Object> progress(long userId,long videoId,int seconds){publicVideo(videoId);int updated=jdbc.update("UPDATE play_records SET progress=?,finished=?,updated_at=? WHERE user_id=? AND video_id=?",seconds,false,Timestamp.from(Instant.now()),userId,videoId);if(updated==0)jdbc.update("INSERT INTO play_records(user_id,video_id,progress,finished,updated_at) VALUES(?,?,?,?,?)",userId,videoId,seconds,false,Timestamp.from(Instant.now()));return Map.of("saved",true,"progress",seconds);}
    public List<Map<String,Object>> ranking(String type,String period,Long categoryId,Long viewer){List<Video> list=videos.findAll().stream().filter(v->v.getStatus()==VideoStatus.PUBLISHED&&v.getVisibility()==Visibility.PUBLIC&&(categoryId==null||Objects.equals(v.getCategoryId(),categoryId))).sorted(Comparator.comparingDouble(this::score).reversed()).limit(50).toList();List<Map<String,Object>> out=new ArrayList<>();for(int i=0;i<list.size();i++){Map<String,Object> m=new LinkedHashMap<>();m.put("rank",i+1);m.put("video",views.videoSummary(list.get(i),viewer));m.put("score",Math.round(score(list.get(i))*100d)/100d);m.put("delta",i%4==0?1:0);m.put("trend",i<2?"new":i%4==0?"up":"same");out.add(m);}return out;}
    public Map<String,Object> shorts(String cursor,int size,Long viewer){int offset=parseCursor(cursor);List<Map<String,Object>> all=videos.findAll().stream().filter(v->v.getVideoType()==VideoType.SHORT&&v.getStatus()==VideoStatus.PUBLISHED&&v.getVisibility()==Visibility.PUBLIC).map(v->{Map<String,Object> m=new LinkedHashMap<>(views.videoSummary(v,viewer));m.put("hlsUrl",Objects.requireNonNullElse(v.getHlsUrl(),"/demo/hls/master.m3u8"));return m;}).toList();int to=Math.min(offset+size,all.size());Map<String,Object> result=new LinkedHashMap<>();result.put("items",all.subList(Math.min(offset,to),to));result.put("nextCursor",to<all.size()?String.valueOf(to):null);result.put("hasMore",to<all.size());return result;}
    public Map<String,Object> history(long userId,int page,int size){List<Map<String,Object>> all=jdbc.query("SELECT video_id,progress,finished FROM play_records WHERE user_id=? ORDER BY updated_at DESC",(rs,n)->{Video v=videos.findById(rs.getLong(1)).orElse(null);if(v==null)return null;Map<String,Object> m=new LinkedHashMap<>(views.videoSummary(v,userId));m.put("progress",rs.getInt(2));m.put("finished",rs.getBoolean(3));return m;},userId).stream().filter(Objects::nonNull).toList();return page(all,page,size);}
    public Map<String,Object> favorites(long userId,int page,int size,Long folderId){List<Map<String,Object>> all=jdbc.query("SELECT video_id FROM favorites WHERE user_id=? AND (? IS NULL OR folder_id=?) ORDER BY created_at DESC",(rs,n)->videos.findById(rs.getLong(1)).map(v->views.videoSummary(v,userId)).orElse(null),userId,folderId,folderId).stream().filter(Objects::nonNull).toList();Map<String,Object> result=new LinkedHashMap<>(page(all,page,size));result.put("folders",jdbc.query("SELECT f.id,f.name,COUNT(v.video_id) amount,f.system_type FROM folders f LEFT JOIN favorites v ON v.folder_id=f.id WHERE f.user_id=? GROUP BY f.id,f.name,f.system_type",(rs,n)->Map.of("id",rs.getLong(1),"name",rs.getString(2),"count",rs.getLong(3),"isDefault",rs.getString(4)!=null),userId));return result;}
    public List<Map<String,Object>> playlists(long userId){return jdbc.query("SELECT p.id,p.name,COUNT(pv.video_id) amount FROM playlists p LEFT JOIN playlist_videos pv ON pv.playlist_id=p.id WHERE p.user_id=? GROUP BY p.id,p.name",(rs,n)->{Map<String,Object>m=new LinkedHashMap<>();m.put("id",rs.getLong(1));m.put("name",rs.getString(2));m.put("count",rs.getLong(3));m.put("cover","/favicon.svg");return m;},userId);}
    @Transactional public Map<String,Object> reaction(long userId,long videoId,String type,boolean active){Video v=publicVideo(videoId);boolean existed=views.liked(userId,"VIDEO",videoId,type);if(active&&!existed){jdbc.update("DELETE FROM likes WHERE user_id=? AND target_type='VIDEO' AND target_id=?",userId,videoId);jdbc.update("INSERT INTO likes(user_id,target_type,target_id,type) VALUES(?,?,?,?)",userId,"VIDEO",videoId,type);}if(!active&&existed)jdbc.update("DELETE FROM likes WHERE user_id=? AND target_type='VIDEO' AND target_id=?",userId,videoId);long likes=views.count("SELECT COUNT(*) FROM likes WHERE target_type='VIDEO' AND target_id=? AND type='LIKE'",videoId),dislikes=views.count("SELECT COUNT(*) FROM likes WHERE target_type='VIDEO' AND target_id=? AND type='DISLIKE'",videoId);v.setCounters(v.getViewCount(),likes,dislikes,v.getCommentCount(),v.getFavoriteCount());return Map.of("active",active,"count","LIKE".equals(type)?likes:dislikes);}
    @Transactional public Map<String,Object> favorite(long userId,long videoId,boolean active,Long folderId){Video v=publicVideo(videoId);int exists=jdbc.queryForObject("SELECT COUNT(*) FROM favorites WHERE user_id=? AND video_id=?",Integer.class,userId,videoId);if(active&&exists==0)jdbc.update("INSERT INTO favorites(user_id,video_id,folder_id) VALUES(?,?,?)",userId,videoId,folderId);if(!active&&exists>0)jdbc.update("DELETE FROM favorites WHERE user_id=? AND video_id=?",userId,videoId);long count=views.count("SELECT COUNT(*) FROM favorites WHERE video_id=?",videoId);v.setCounters(v.getViewCount(),v.getLikeCount(),v.getDislikeCount(),v.getCommentCount(),count);return Map.of("active",active,"count",count);}
    @Transactional public Map<String,Object> subscribe(long userId,long videoId,boolean active){Video v=publicVideo(videoId);int exists=jdbc.queryForObject("SELECT COUNT(*) FROM subscriptions WHERE user_id=? AND target_type='USER' AND target_id=?",Integer.class,userId,v.getUserId());if(active&&exists==0)jdbc.update("INSERT INTO subscriptions(user_id,target_type,target_id) VALUES(?,?,?)",userId,"USER",v.getUserId());if(!active&&exists>0)jdbc.update("DELETE FROM subscriptions WHERE user_id=? AND target_type='USER' AND target_id=?",userId,v.getUserId());return Map.of("active",active);}
    @Transactional public Map<String,Object> download(long userId,long videoId){Video v=publicVideo(videoId);if(!v.isDownloadEnabled())throw new ApiException(ErrorCode.FORBIDDEN,"作者未开放下载");jdbc.update("INSERT INTO download_records(user_id,video_id,quality) VALUES(?,?,?)",userId,videoId,"720p");return Map.of("url",Objects.requireNonNullElse(v.getHlsUrl(),"/demo/hls/master.m3u8"),"expiresIn",600,"quality","720p");}
    public Map<String,Object> comments(long videoId,String sort,int page,int size,Long viewer){publicVideo(videoId);String order="hot".equals(sort)?"like_count DESC,created_at DESC":"created_at DESC";List<Map<String,Object>> all=jdbc.query("SELECT * FROM comments WHERE video_id=? AND parent_id IS NULL AND status='VISIBLE' ORDER BY "+order,(rs,n)->comment(rs,viewer),videoId);return page(all,page,size);}
    @Transactional public Map<String,Object> addComment(long userId,long videoId,Long parentId,String content){if(content==null||content.isBlank()||content.length()>1000)throw new ApiException(ErrorCode.VALIDATION,"评论长度应为 1-1000 字");Video v=publicVideo(videoId);Long rootId=null;if(parentId!=null){Map<String,Object> parent=jdbc.queryForMap("SELECT root_id FROM comments WHERE id=?",parentId);rootId=parent.get("root_id")==null?parentId:((Number)parent.get("root_id")).longValue();}Map<String,Object> values=new HashMap<>();values.put("video_id",videoId);values.put("user_id",userId);values.put("parent_id",parentId);values.put("root_id",rootId);values.put("content",sanitize(content));values.put("status","VISIBLE");Number id=new SimpleJdbcInsert(jdbc).withTableName("comments").usingGeneratedKeyColumns("id").usingColumns("video_id","user_id","parent_id","root_id","content","status").executeAndReturnKey(values);if(parentId!=null)jdbc.update("UPDATE comments SET reply_count=reply_count+1 WHERE id=?",rootId);v.setCounters(v.getViewCount(),v.getLikeCount(),v.getDislikeCount(),v.getCommentCount()+1,v.getFavoriteCount());return commentById(id.longValue(),userId);}
    public Map<String,Object> replies(long commentId,int page,int size,Long viewer){List<Map<String,Object>> all=jdbc.query("SELECT * FROM comments WHERE (parent_id=? OR root_id=?) AND status='VISIBLE' ORDER BY created_at",(rs,n)->comment(rs,viewer),commentId,commentId);return page(all,page,size);}
    @Transactional public Map<String,Object> likeComment(long userId,long id,boolean active){boolean existed=views.liked(userId,"COMMENT",id,"LIKE");if(active&&!existed)jdbc.update("INSERT INTO likes(user_id,target_type,target_id,type) VALUES(?,?,?,?)",userId,"COMMENT",id,"LIKE");if(!active&&existed)jdbc.update("DELETE FROM likes WHERE user_id=? AND target_type='COMMENT' AND target_id=?",userId,id);long count=views.count("SELECT COUNT(*) FROM likes WHERE target_type='COMMENT' AND target_id=?",id);jdbc.update("UPDATE comments SET like_count=? WHERE id=?",count,id);return Map.of("active",active,"count",count);}
    @Transactional public void deleteComment(long userId,long id,boolean admin){Map<String,Object> row=jdbc.queryForMap("SELECT user_id FROM comments WHERE id=?",id);if(((Number)row.get("user_id")).longValue()!=userId&&!admin)throw new ApiException(ErrorCode.FORBIDDEN,"不能删除他人的评论");jdbc.update("UPDATE comments SET status='DELETED',content='该评论已删除' WHERE id=?",id);}
    public Map<String,Object> commentById(long id,Long viewer){List<Map<String,Object>> rows=jdbc.query("SELECT * FROM comments WHERE id=?",(rs,n)->comment(rs,viewer),id);if(rows.isEmpty())throw new ApiException(ErrorCode.NOT_FOUND,"评论不存在");return rows.get(0);}
    private Map<String,Object> comment(ResultSet rs,Long viewer)throws SQLException{Map<String,Object>m=new LinkedHashMap<>();long id=rs.getLong("id"),userId=rs.getLong("user_id"),videoId=rs.getLong("video_id");m.put("id",id);m.put("videoId",videoId);m.put("parentId",nullableLong(rs,"parent_id"));m.put("rootId",nullableLong(rs,"root_id"));m.put("content",rs.getString("content"));m.put("user",views.brief(userId));m.put("likeCount",rs.getLong("like_count"));m.put("replyCount",rs.getLong("reply_count"));m.put("liked",viewer!=null&&views.liked(viewer,"COMMENT",id,"LIKE"));m.put("status",rs.getString("status"));m.put("createdAt",rs.getTimestamp("created_at").toInstant());Long author=jdbc.queryForObject("SELECT user_id FROM videos WHERE id=?",Long.class,videoId);m.put("isVideoAuthor",Objects.equals(author,userId));return m;}
    private Long nullableLong(ResultSet rs,String column)throws SQLException{long v=rs.getLong(column);return rs.wasNull()?null:v;}
    private Video publicVideo(long id){Video v=videos.findById(id).orElseThrow(()->new ApiException(ErrorCode.NOT_FOUND,"视频不存在"));if(v.getStatus()!=VideoStatus.PUBLISHED&&v.getStatus()!=VideoStatus.REVIEWING)throw new ApiException(ErrorCode.NOT_FOUND,"视频不存在");return v;}
    private double score(Video v){return .4*Math.log1p(v.getViewCount())+1.5*Math.log1p(v.getLikeCount())+2*Math.log1p(v.getCommentCount())+1.8*Math.log1p(v.getFavoriteCount());}
    private int parseCursor(String cursor){try{return cursor==null?0:Math.max(0,Integer.parseInt(cursor));}catch(NumberFormatException ex){return 0;}}
    private Map<String,Object> page(List<?> all,int page,int size){int from=Math.min((page-1)*size,all.size()),to=Math.min(from+size,all.size());Map<String,Object>m=new LinkedHashMap<>();m.put("items",all.subList(from,to));m.put("total",all.size());m.put("page",page);m.put("pageSize",size);m.put("hasMore",to<all.size());return m;}
    private String sanitize(String text){return text.replaceAll("<[^>]*>","").trim();}
}
