package com.videoshare.interaction;

import com.videoshare.auth.CurrentUser;import com.videoshare.common.*;import jakarta.servlet.http.HttpServletRequest;import jakarta.validation.constraints.Max;import java.util.*;import org.springframework.security.core.annotation.AuthenticationPrincipal;import org.springframework.web.bind.annotation.*;

@RestController @RequestMapping("/api/v1")
public class InteractionController {
    private final InteractionService service;private final IdempotencyService idempotency;public InteractionController(InteractionService service,IdempotencyService idempotency){this.service=service;this.idempotency=idempotency;}
    @GetMapping("/videos/{id}/play")public ApiResponse<Map<String,Object>>play(@PathVariable long id,@AuthenticationPrincipal CurrentUser c){return ApiResponse.ok(service.play(id,c==null?null:c.id()));}
    @GetMapping("/videos/{id}/related")public ApiResponse<List<Map<String,Object>>>related(@PathVariable long id,@AuthenticationPrincipal CurrentUser c){return ApiResponse.ok(service.related(id,c==null?null:c.id()));}
    @PostMapping("/videos/{id}/view")public ApiResponse<Map<String,Object>>view(@PathVariable long id,@AuthenticationPrincipal CurrentUser c,@RequestHeader(name="Idempotency-Key",required=false)String key,HttpServletRequest req){long user=c==null?0:c.id();return ApiResponse.ok(idempotency.execute(user,"video:view:"+id,key,()->service.view(id,c==null?req.getRemoteAddr():"u"+c.id())));}
    @PostMapping("/videos/{id}/progress")public ApiResponse<Map<String,Object>>progress(@PathVariable long id,@AuthenticationPrincipal CurrentUser c,@RequestBody Map<String,Number>b){return ApiResponse.ok(service.progress(require(c),id,Math.max(0,b.getOrDefault("progress",0).intValue())));}
    @GetMapping("/videos/ranking")public ApiResponse<List<Map<String,Object>>>ranking(@RequestParam(defaultValue="hot")String type,@RequestParam(defaultValue="daily")String period,@RequestParam(required=false)Long categoryId,@AuthenticationPrincipal CurrentUser c){return ApiResponse.ok(service.ranking(type,period,categoryId,c==null?null:c.id()));}
    @GetMapping("/videos/shorts")public ApiResponse<Map<String,Object>>shorts(@RequestParam(required=false)String cursor,@RequestParam(defaultValue="10")@Max(50)int pageSize,@AuthenticationPrincipal CurrentUser c){return ApiResponse.ok(service.shorts(cursor,Math.min(pageSize,50),c==null?null:c.id()));}
    @GetMapping("/videos/history")public ApiResponse<PageResult<Map<String,Object>>>history(@AuthenticationPrincipal CurrentUser c,@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="20")@Max(100)int pageSize){return ApiResponse.ok(service.history(require(c),page,pageSize));}
    @GetMapping("/videos/favorites")public ApiResponse<Map<String,Object>>favorites(@AuthenticationPrincipal CurrentUser c,@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="20")@Max(100)int pageSize,@RequestParam(required=false)Long folderId){return ApiResponse.ok(service.favorites(require(c),page,pageSize,folderId));}
    @GetMapping("/videos/playlists")public ApiResponse<List<Map<String,Object>>>playlists(@AuthenticationPrincipal CurrentUser c){return ApiResponse.ok(service.playlists(require(c)));}
    @GetMapping("/videos/playlists/{playlistId}")public ApiResponse<List<Map<String,Object>>>playlistVideos(@PathVariable long playlistId,@AuthenticationPrincipal CurrentUser c){return ApiResponse.ok(service.playlistVideos(require(c),playlistId));}
    @PostMapping("/videos/playlists")public ApiResponse<Map<String,Object>>createPlaylist(@AuthenticationPrincipal CurrentUser c,@RequestBody Map<String,String>b){return ApiResponse.ok(service.createPlaylist(require(c),b.get("name"),b.get("description")));}
    @PostMapping("/videos/playlists/{playlistId}/videos")public ApiResponse<Map<String,Boolean>>addPlaylistVideo(@PathVariable long playlistId,@AuthenticationPrincipal CurrentUser c,@RequestBody Map<String,Number>b){service.addPlaylistVideo(require(c),playlistId,b.get("videoId")==null?0:b.get("videoId").longValue());return ApiResponse.ok(Map.of("success",true));}
    @DeleteMapping("/videos/playlists/{playlistId}/videos/{videoId}")public ApiResponse<Map<String,Boolean>>removePlaylistVideo(@PathVariable long playlistId,@PathVariable long videoId,@AuthenticationPrincipal CurrentUser c){service.removePlaylistVideo(require(c),playlistId,videoId);return ApiResponse.ok(Map.of("success",true));}
    @DeleteMapping("/videos/playlists/{playlistId}")public ApiResponse<Map<String,Boolean>>deletePlaylist(@PathVariable long playlistId,@AuthenticationPrincipal CurrentUser c){service.deletePlaylist(require(c),playlistId);return ApiResponse.ok(Map.of("success",true));}
    @PostMapping("/videos/{id}/like")public ApiResponse<Map<String,Object>>like(@PathVariable long id,@AuthenticationPrincipal CurrentUser c,@RequestBody Map<String,String>b){return ApiResponse.ok(service.reaction(require(c),id,"LIKE","LIKE".equals(b.get("action"))));}
    @PostMapping("/videos/{id}/dislike")public ApiResponse<Map<String,Object>>dislike(@PathVariable long id,@AuthenticationPrincipal CurrentUser c,@RequestBody Map<String,String>b){return ApiResponse.ok(service.reaction(require(c),id,"DISLIKE","DISLIKE".equals(b.get("action"))));}
    @PostMapping("/videos/{id}/favorite")public ApiResponse<Map<String,Object>>favorite(@PathVariable long id,@AuthenticationPrincipal CurrentUser c,@RequestBody Map<String,Object>b){Long folder=b.get("folderId")instanceof Number n?n.longValue():null;return ApiResponse.ok(service.favorite(require(c),id,"FAVORITE".equals(b.get("action")),folder));}
    @PostMapping("/videos/{id}/subscribe")public ApiResponse<Map<String,Object>>subscribe(@PathVariable long id,@AuthenticationPrincipal CurrentUser c,@RequestBody Map<String,String>b){return ApiResponse.ok(service.subscribe(require(c),id,"SUBSCRIBE".equals(b.get("action"))));}
    @GetMapping("/videos/{id}/download")public ApiResponse<Map<String,Object>>download(@PathVariable long id,@AuthenticationPrincipal CurrentUser c){return ApiResponse.ok(service.download(require(c),id));}
    @GetMapping("/videos/{id}/comments")public ApiResponse<PageResult<Map<String,Object>>>comments(@PathVariable long id,@RequestParam(defaultValue="new")String sort,@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="20")@Max(100)int pageSize,@AuthenticationPrincipal CurrentUser c){return ApiResponse.ok(service.comments(id,sort,page,pageSize,c==null?null:c.id()));}
    @PostMapping("/videos/{id}/comments")public ApiResponse<Map<String,Object>>comment(@PathVariable long id,@AuthenticationPrincipal CurrentUser c,@RequestHeader(name="Idempotency-Key",required=false)String key,@RequestBody Map<String,String>b){long user=require(c);return ApiResponse.ok(idempotency.execute(user,"video:comment:"+id,key,()->service.addComment(user,id,null,b.get("content"))));}
    @GetMapping("/comments/{id}/replies")public ApiResponse<PageResult<Map<String,Object>>>replies(@PathVariable long id,@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="10")@Max(100)int pageSize,@AuthenticationPrincipal CurrentUser c){return ApiResponse.ok(service.replies(id,page,pageSize,c==null?null:c.id()));}
    @PostMapping("/comments/{id}/reply")public ApiResponse<Map<String,Object>>reply(@PathVariable long id,@AuthenticationPrincipal CurrentUser c,@RequestHeader(name="Idempotency-Key",required=false)String key,@RequestBody Map<String,String>b){long user=require(c);return ApiResponse.ok(idempotency.execute(user,"comment:reply:"+id,key,()->{Map<String,Object>parent=service.commentById(id,user);return service.addComment(user,((Number)parent.get("videoId")).longValue(),id,b.get("content"));}));}
    @PostMapping("/comments/{id}/like")public ApiResponse<Map<String,Object>>likeComment(@PathVariable long id,@AuthenticationPrincipal CurrentUser c,@RequestBody Map<String,String>b){return ApiResponse.ok(service.likeComment(require(c),id,"LIKE".equals(b.get("action"))));}
    @DeleteMapping("/comments/{id}")public ApiResponse<Map<String,Boolean>>deleteComment(@PathVariable long id,@AuthenticationPrincipal CurrentUser c){service.deleteComment(require(c),id,c.role()==com.videoshare.user.Role.ADMIN);return ApiResponse.ok(Map.of("success",true));}
    private long require(CurrentUser c){if(c==null)throw new ApiException(ErrorCode.UNAUTHORIZED,"请先登录");return c.id();}
}
