package com.videoshare.common;

import com.videoshare.user.*;
import com.videoshare.video.Video;
import java.util.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
public class ViewFactory {
    private final UserRepository users; private final JdbcTemplate jdbc;
    public ViewFactory(UserRepository users,JdbcTemplate jdbc){this.users=users;this.jdbc=jdbc;}
    public Map<String,Object> brief(long userId){User u=users.findById(userId).orElseThrow(()->new ApiException(ErrorCode.NOT_FOUND,"用户不存在"));Map<String,Object> m=new LinkedHashMap<>();m.put("id",u.getId());m.put("username",u.getUsername());m.put("nickname",u.getNickname());m.put("avatar",u.getAvatarUrl());m.put("bio",u.getBio());m.put("certified",bool("SELECT COUNT(*)>0 FROM creator_profiles WHERE user_id=? AND auth_status='CERTIFIED'",userId));m.put("followerCount",count("SELECT COUNT(*) FROM follows WHERE followee_id=?",userId));return m;}
    public Map<String,Object> profile(long userId,Long viewer,boolean own){User u=users.findById(userId).orElseThrow(()->new ApiException(ErrorCode.NOT_FOUND,"用户不存在"));Map<String,Object> m=new LinkedHashMap<>(brief(userId));boolean certified=(boolean)m.get("certified");m.put("role",u.getRole().name());m.put("status",u.getStatus().name());m.put("permissions",permissions(u.getRole(),certified));m.put("followingCount",count("SELECT COUNT(*) FROM follows WHERE follower_id=?",userId));m.put("videoCount",count("SELECT COUNT(*) FROM videos WHERE user_id=? AND status='PUBLISHED'",userId));m.put("totalViews",count("SELECT COALESCE(SUM(view_count),0) FROM videos WHERE user_id=?",userId));m.put("totalLikes",count("SELECT COALESCE(SUM(like_count),0) FROM videos WHERE user_id=?",userId));m.put("createdAt",u.getCreatedAt());boolean followed=viewer!=null&&bool("SELECT COUNT(*)>0 FROM follows WHERE follower_id=? AND followee_id=?",viewer,userId);boolean mutual=followed&&bool("SELECT COUNT(*)>0 FROM follows WHERE follower_id=? AND followee_id=?",userId,viewer);m.put("followed",followed);m.put("mutual",mutual);m.put("subscribed",viewer!=null&&bool("SELECT COUNT(*)>0 FROM subscriptions WHERE user_id=? AND target_type='USER' AND target_id=?",viewer,userId));if(own){m.put("email",u.getEmail());m.put("phone",maskPhone(u.getPhone()));m.put("realNameStatus",certified?"CERTIFIED":"NONE");}return m;}
    public Map<String,Object> category(long id){List<Map<String,Object>> rows=jdbc.query("SELECT id,name,slug,sort_order FROM categories WHERE id=?",(rs,n)->{Map<String,Object> m=new LinkedHashMap<>();m.put("id",rs.getLong("id"));m.put("name",rs.getString("name"));m.put("slug",rs.getString("slug"));m.put("sortOrder",rs.getInt("sort_order"));return m;},id);return rows.isEmpty()?null:rows.get(0);}
    public Map<String,Object> videoSummary(Video v,Long viewer){Map<String,Object> m=new LinkedHashMap<>();m.put("id",v.getId());m.put("videoType",v.getVideoType().name());m.put("title",v.getTitle());m.put("coverUrl",Objects.requireNonNullElse(v.getCoverUrl(),"/favicon.svg"));m.put("duration",v.getDuration());m.put("category",category(v.getCategoryId()));m.put("author",brief(v.getUserId()));Map<String,Object> stats=new LinkedHashMap<>();stats.put("views",v.getViewCount());stats.put("likes",v.getLikeCount());stats.put("dislikes",v.getDislikeCount());stats.put("comments",v.getCommentCount());stats.put("favorites",v.getFavoriteCount());stats.put("shares",0);m.put("stats",stats);m.put("publishedAt",Objects.requireNonNullElse(v.getPublishedAt(),v.getCreatedAt()));m.put("status",v.getStatus().name());m.put("visibility",v.getVisibility().name());m.put("recommendReason","根据你的兴趣推荐");m.put("liked",viewer!=null&&liked(viewer,"VIDEO",v.getId(),"LIKE"));m.put("favorited",viewer!=null&&bool("SELECT COUNT(*)>0 FROM favorites WHERE user_id=? AND video_id=?",viewer,v.getId()));return m;}
    public Map<String,Object> videoDetail(Video v,Long viewer){Map<String,Object> m=new LinkedHashMap<>(videoSummary(v,viewer));m.put("description",Objects.requireNonNullElse(v.getDescription(),""));m.put("tags",jdbc.query("SELECT t.tag_name FROM tags t JOIN video_tags vt ON vt.tag_id=t.id WHERE vt.video_id=?",(rs,n)->rs.getString(1),v.getId()));m.put("qualities",List.of("source"));m.put("hlsUrl",v.getHlsUrl()!=null&&!v.getHlsUrl().startsWith("/demo/")?v.getHlsUrl():"/api/v1/videos/"+v.getId()+"/source");m.put("downloadEnabled",v.isDownloadEnabled());m.put("createdAt",v.getCreatedAt());m.put("updatedAt",v.getUpdatedAt());m.put("liked",viewer!=null&&liked(viewer,"VIDEO",v.getId(),"LIKE"));m.put("disliked",viewer!=null&&liked(viewer,"VIDEO",v.getId(),"DISLIKE"));m.put("favorited",viewer!=null&&bool("SELECT COUNT(*)>0 FROM favorites WHERE user_id=? AND video_id=?",viewer,v.getId()));m.put("subscribed",viewer!=null&&bool("SELECT COUNT(*)>0 FROM subscriptions WHERE user_id=? AND target_type='USER' AND target_id=?",viewer,v.getUserId()));m.put("reviewNote",v.getReviewNote());return m;}
    public boolean liked(long userId,String targetType,long targetId,String type){return bool("SELECT COUNT(*)>0 FROM likes WHERE user_id=? AND target_type=? AND target_id=? AND type=?",userId,targetType,targetId,type);}
    public long count(String sql,Object...args){Number n=jdbc.queryForObject(sql,Number.class,args);return n==null?0:n.longValue();}
    public boolean bool(String sql,Object...args){Boolean b=jdbc.queryForObject(sql,Boolean.class,args);return Boolean.TRUE.equals(b);}
    public List<String> permissions(Role role,boolean creator){List<String> result=new ArrayList<>(List.of("video:upload","video:manage_own"));if(creator)result.addAll(List.of("video:download","creator:dashboard"));if(role==Role.MODERATOR||role==Role.ADMIN)result.addAll(List.of("moderation:review","moderation:report"));if(role==Role.ADMIN)result.addAll(List.of("admin:user_manage","admin:role_assign","admin:system_config","admin:analytics"));return result;}
    private String maskPhone(String value){return value==null?null:value.replaceAll("(\\d{3})\\d{4}(\\d{4})","$1****$2");}
}
