package com.videoshare.media;

import com.videoshare.common.*;import io.minio.*;import io.minio.http.Method;import io.minio.messages.DeleteObject;import io.minio.messages.Item;import jakarta.annotation.PostConstruct;import java.util.*;import java.util.concurrent.TimeUnit;import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;import org.springframework.stereotype.Component;

@Component @ConditionalOnProperty(name="app.storage.mode",havingValue="minio")
public class MinioStorageGateway implements StorageGateway {
    private final MinioClient client;private final MinioClient publicClient;private final StorageProperties p;
    public MinioStorageGateway(StorageProperties p){this.p=p;this.client=MinioClient.builder().endpoint(p.endpoint()).credentials(p.accessKey(),p.secretKey()).build();String publicEndpoint=p.publicEndpoint()==null||p.publicEndpoint().isBlank()?p.endpoint():p.publicEndpoint();this.publicClient=MinioClient.builder().endpoint(publicEndpoint).credentials(p.accessKey(),p.secretKey()).build();}
    @PostConstruct void bucketReady(){try{if(!client.bucketExists(BucketExistsArgs.builder().bucket(p.bucket()).build()))client.makeBucket(MakeBucketArgs.builder().bucket(p.bucket()).build());}catch(Exception ex){throw new IllegalStateException("MinIO 初始化失败",ex);}}
    public String partUrl(String id,int part){try{return publicClient.getPresignedObjectUrl(GetPresignedObjectUrlArgs.builder().method(Method.PUT).bucket(p.bucket()).object(partKey(id,part)).expiry(2,TimeUnit.HOURS).build());}catch(Exception ex){throw new ApiException(ErrorCode.INTERNAL,"无法生成上传地址");}}
    public String complete(String id,String sha,List<Integer> parts,long expectedSize,String fileName){String object="source/"+sha+".bin";try{List<ComposeSource> sources=parts.stream().map(n->ComposeSource.builder().bucket(p.bucket()).object(partKey(id,n)).build()).toList();client.composeObject(ComposeObjectArgs.builder().bucket(p.bucket()).object(object).sources(sources).build());long actualSize=client.statObject(StatObjectArgs.builder().bucket(p.bucket()).object(object).build()).size();if(actualSize!=expectedSize){client.removeObject(RemoveObjectArgs.builder().bucket(p.bucket()).object(object).build());throw new ApiException(ErrorCode.VALIDATION,"合并后的文件大小不一致");}try(java.io.InputStream input=client.getObject(GetObjectArgs.builder().bucket(p.bucket()).object(object).offset(0L).length(32L).build())){StorageGateway.validateVideoHeader(input.readNBytes(32),fileName);}catch(ApiException ex){client.removeObject(RemoveObjectArgs.builder().bucket(p.bucket()).object(object).build());throw ex;}abort(id);return object;}catch(ApiException ex){throw ex;}catch(Exception ex){throw new ApiException(ErrorCode.INTERNAL,"MinIO 分片合并失败");}}
    public void abort(String id){try{List<DeleteObject> objects=new ArrayList<>();for(Result<Item> item:client.listObjects(ListObjectsArgs.builder().bucket(p.bucket()).prefix("uploads/"+id+"/").build()))objects.add(new DeleteObject(item.get().objectName()));for(var result:client.removeObjects(RemoveObjectsArgs.builder().bucket(p.bucket()).objects(objects).build()))result.get();}catch(Exception ignored){}}
    public String bucket(){return p.bucket();}private String partKey(String id,int part){return "uploads/"+id+"/part-"+part;}
}
