package com.videoshare.admin;

import com.videoshare.auth.CurrentUser;import com.videoshare.common.*;import com.videoshare.user.*;import java.util.*;import org.springframework.security.core.annotation.AuthenticationPrincipal;import org.springframework.web.bind.annotation.*;

@RestController @RequestMapping("/api/v1/admin")
public class AdminController {
    private final AdminService service;private final IdempotencyService idempotency;public AdminController(AdminService service,IdempotencyService idempotency){this.service=service;this.idempotency=idempotency;}
    @GetMapping("/overview")public ApiResponse<Map<String,Object>>overview(@AuthenticationPrincipal CurrentUser c){admin(c);return ApiResponse.ok(service.overview());}
    @GetMapping("/reviews")public ApiResponse<Map<String,Object>>reviews(@AuthenticationPrincipal CurrentUser c,@RequestParam(required=false)String status,@RequestParam(required=false)String riskLevel,@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="10")int pageSize){moderator(c);return ApiResponse.ok(service.reviews(status,riskLevel,page,pageSize));}
    @PostMapping("/reviews/{id}/decision")public ApiResponse<Map<String,Object>>decide(@PathVariable long id,@AuthenticationPrincipal CurrentUser c,@RequestHeader(name="Idempotency-Key",required=false)String key,@RequestBody Map<String,String>b){moderator(c);return ApiResponse.ok(idempotency.execute(c.id(),"admin:review:"+id,key,()->service.decide(c.id(),id,b.get("decision"),b.get("note"))));}
    @GetMapping("/reports")public ApiResponse<Map<String,Object>>reports(@AuthenticationPrincipal CurrentUser c,@RequestParam(required=false)String status,@RequestParam(required=false)String reason,@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="10")int pageSize){moderator(c);return ApiResponse.ok(service.reports(status,reason,page,pageSize));}
    @PostMapping("/reports/{id}/handle")public ApiResponse<Map<String,Object>>handle(@PathVariable long id,@AuthenticationPrincipal CurrentUser c,@RequestHeader(name="Idempotency-Key",required=false)String key,@RequestBody Map<String,String>b){moderator(c);return ApiResponse.ok(idempotency.execute(c.id(),"admin:report:"+id,key,()->service.handleReport(c.id(),id,b.getOrDefault("status","RESOLVED"),b.get("note"))));}
    @GetMapping("/users")public ApiResponse<Map<String,Object>>users(@AuthenticationPrincipal CurrentUser c,@RequestParam(required=false)String keyword,@RequestParam(required=false)String role,@RequestParam(required=false)String status,@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="10")int pageSize){admin(c);return ApiResponse.ok(service.users(keyword,role,status,page,pageSize));}
    @PutMapping("/users/{id}/status")public ApiResponse<Map<String,Object>>status(@PathVariable long id,@AuthenticationPrincipal CurrentUser c,@RequestBody Map<String,String>b){admin(c);return ApiResponse.ok(service.status(c.id(),id,UserStatus.valueOf(b.get("status")),b.get("reason")));}
    @PutMapping("/users/{id}/role")public ApiResponse<Map<String,Object>>role(@PathVariable long id,@AuthenticationPrincipal CurrentUser c,@RequestBody Map<String,String>b){admin(c);return ApiResponse.ok(service.role(c.id(),id,Role.valueOf(b.get("role"))));}
    @GetMapping("/videos")public ApiResponse<Map<String,Object>>videos(@AuthenticationPrincipal CurrentUser c,@RequestParam(required=false)String status,@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="10")int pageSize){moderator(c);return ApiResponse.ok(service.videos(status,page,pageSize));}
    @GetMapping("/audit-logs")public ApiResponse<Map<String,Object>>logs(@AuthenticationPrincipal CurrentUser c,@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="15")int pageSize){admin(c);return ApiResponse.ok(service.auditLogs(page,pageSize));}
    @GetMapping("/settings")public ApiResponse<Map<String,Object>>settings(@AuthenticationPrincipal CurrentUser c){admin(c);return ApiResponse.ok(service.settings());}
    @PutMapping("/settings")public ApiResponse<Map<String,Object>>settings(@AuthenticationPrincipal CurrentUser c,@RequestBody Map<String,Object>b){admin(c);return ApiResponse.ok(service.settings(c.id(),b));}
    private void moderator(CurrentUser c){if(c==null||(c.role()!=Role.MODERATOR&&c.role()!=Role.ADMIN))throw new ApiException(ErrorCode.FORBIDDEN,"需要审核权限");}private void admin(CurrentUser c){if(c==null||c.role()!=Role.ADMIN)throw new ApiException(ErrorCode.FORBIDDEN,"需要管理员权限");}
}
