package com.videoshare.admin;

import com.fasterxml.jackson.core.type.TypeReference;import com.fasterxml.jackson.databind.ObjectMapper;import com.videoshare.auth.CurrentUser;import com.videoshare.common.*;import com.videoshare.user.*;import com.videoshare.video.*;import java.sql.*;import java.time.*;import java.util.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.jdbc.core.simple.SimpleJdbcInsert;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;

@Service
public class AdminService {
    private final JdbcTemplate jdbc;private final UserRepository users;private final VideoRepository videos;private final ViewFactory views;private final ObjectMapper json;
    public AdminService(JdbcTemplate jdbc,UserRepository users,VideoRepository videos,ViewFactory views,ObjectMapper json){this.jdbc=jdbc;this.users=users;this.videos=videos;this.views=views;this.json=json;}
    public Map<String,Object> overview(){LocalDate today=LocalDate.now();Timestamp start=Timestamp.valueOf(today.atStartOfDay());Map<String,Object> out=new LinkedHashMap<>();out.put("users",Map.of("total",users.count(),"todayNew",views.count("SELECT COUNT(*) FROM users WHERE created_at>=?",start),"activeToday",views.count("SELECT COUNT(*) FROM users WHERE last_login_at>=?",start),"banned",views.count("SELECT COUNT(*) FROM users WHERE status='BANNED'")));out.put("videos",Map.of("total",videos.count(),"todayNew",views.count("SELECT COUNT(*) FROM videos WHERE created_at>=?",start),"processing",views.count("SELECT COUNT(*) FROM videos WHERE status='PROCESSING'"),"reviewing",views.count("SELECT COUNT(*) FROM videos WHERE status='REVIEWING'")));out.put("interaction",Map.of("commentsToday",views.count("SELECT COUNT(*) FROM comments WHERE created_at>=?",start),"likesToday",views.count("SELECT COUNT(*) FROM likes WHERE created_at>=?",start),"reportsPending",views.count("SELECT COUNT(*) FROM reports WHERE status='PENDING'")));Number avg=jdbc.queryForObject("SELECT COALESCE(AVG(DATEDIFF('SECOND',started_at,completed_at)),0) FROM transcode_tasks WHERE status='SUCCESS' AND completed_at IS NOT NULL",Number.class);out.put("transcode",Map.of("queued",views.count("SELECT COUNT(*) FROM transcode_tasks WHERE status='QUEUED'"),"running",views.count("SELECT COUNT(*) FROM transcode_tasks WHERE status='RUNNING'"),"failedToday",views.count("SELECT COUNT(*) FROM transcode_tasks WHERE status='FAILED' AND created_at>=?",start),"avgSeconds",avg==null?0:avg.doubleValue()));List<Map<String,Object>> trend=new ArrayList<>();for(int i=13;i>=0;i--){LocalDate day=today.minusDays(i);Timestamp from=Timestamp.valueOf(day.atStartOfDay()),to=Timestamp.valueOf(day.plusDays(1).atStartOfDay());trend.add(Map.of("date",day,"uploads",views.count("SELECT COUNT(*) FROM videos WHERE created_at>=? AND created_at<?",from,to),"views",views.count("SELECT COALESCE(SUM(view_count),0) FROM videos WHERE updated_at>=? AND updated_at<?",from,to),"newUsers",views.count("SELECT COUNT(*) FROM users WHERE created_at>=? AND created_at<?",from,to)));}out.put("trend",trend);out.put("categoryDistribution",jdbc.query("SELECT c.name,COUNT(v.id) amount FROM categories c LEFT JOIN videos v ON v.category_id=c.id GROUP BY c.name",(rs,n)->Map.of("name",rs.getString(1),"value",rs.getLong(2))));return out;}
    public Map<String,Object> reviews(String status,String risk,int page,int size){List<Map<String,Object>> all=jdbc.query("SELECT r.*,v.id video_id FROM video_reviews r JOIN videos v ON v.id=r.video_id ORDER BY r.submitted_at DESC",(rs,n)->{String s=rs.getString("status"),level=rs.getString("risk_level");if(status!=null&&!status.equals("ALL")&&!status.equals(s))return null;if(risk!=null&&!risk.equals("ALL")&&!risk.equals(level))return null;Video v=videos.findById(rs.getLong("video_id")).orElseThrow();Map<String,Object>m=new LinkedHashMap<>();m.put("id",rs.getLong("id"));m.put("video",views.videoSummary(v,null));m.put("machineResult",rs.getString("machine_result"));m.put("machineLabels",List.of());m.put("riskLevel",level);m.put("reportCount",views.count("SELECT COUNT(*) FROM reports WHERE target_type='VIDEO' AND target_id=?",v.getId()));m.put("submittedAt",rs.getTimestamp("submitted_at").toInstant());m.put("status",s);m.put("reviewerId",nullable(rs,"reviewer_id"));m.put("reviewNote",rs.getString("review_note"));return m;}).stream().filter(Objects::nonNull).toList();return page(all,page,size);}
    @Transactional public Map<String,Object> decide(long operator,long taskId,String decision,String note){Map<String,Object>task=jdbc.queryForMap("SELECT video_id FROM video_reviews WHERE id=?",taskId);boolean approve="APPROVE".equals(decision);String status=approve?"APPROVED":"REJECTED";jdbc.update("UPDATE video_reviews SET status=?,reviewer_id=?,review_note=?,reviewed_at=? WHERE id=?",status,operator,note,Timestamp.from(Instant.now()),taskId);Video v=videos.findById(((Number)task.get("video_id")).longValue()).orElseThrow();v.review(approve,note);audit(operator,"REVIEW_"+decision,"VIDEO",v.getId(),Map.of("note",Objects.toString(note,"")));return Map.of("success",true,"status",status);}
    public Map<String,Object> reports(String status,String reason,int page,int size){List<Map<String,Object>> all=jdbc.query("SELECT * FROM reports ORDER BY priority DESC,created_at DESC",(rs,n)->{if(status!=null&&!status.equals("ALL")&&!status.equals(rs.getString("status")))return null;if(reason!=null&&!reason.equals("ALL")&&!reason.equals(rs.getString("reason")))return null;Map<String,Object>m=new LinkedHashMap<>();m.put("id",rs.getLong("id"));m.put("targetType",rs.getString("target_type"));m.put("targetId",rs.getLong("target_id"));m.put("targetTitle","被举报内容 #"+rs.getLong("target_id"));m.put("targetSnapshot",Objects.requireNonNullElse(rs.getString("target_snapshot"),""));m.put("reason",rs.getString("reason"));m.put("description",Objects.requireNonNullElse(rs.getString("description"),""));m.put("evidenceUrls",List.of());m.put("reporter",views.brief(rs.getLong("reporter_id")));m.put("status",rs.getString("status"));m.put("priority",rs.getInt("priority"));m.put("handlerId",nullable(rs,"handler_id"));Timestamp handled=rs.getTimestamp("handled_at");m.put("handledAt",handled==null?null:handled.toInstant());m.put("createdAt",rs.getTimestamp("created_at").toInstant());return m;}).stream().filter(Objects::nonNull).toList();return page(all,page,size);}
    @Transactional public Map<String,Object> handleReport(long operator,long id,String status,String note){jdbc.update("UPDATE reports SET status=?,handler_id=?,handled_at=?,handle_note=? WHERE id=?",status,operator,Timestamp.from(Instant.now()),note,id);audit(operator,"REPORT_"+status,"REPORT",id,Map.of("note",Objects.toString(note,"")));return Map.of("success",true,"status",status);}
    public Map<String,Object> users(String keyword,String role,String status,int page,int size){List<Map<String,Object>> all=users.findAll().stream().filter(u->keyword==null||keyword.isBlank()||u.getUsername().toLowerCase().contains(keyword.toLowerCase())||u.getNickname().toLowerCase().contains(keyword.toLowerCase())||u.getEmail().toLowerCase().contains(keyword.toLowerCase())).filter(u->role==null||role.equals("ALL")||u.getRole().name().equals(role)).filter(u->status==null||status.equals("ALL")||u.getStatus().name().equals(status)).map(u->{Map<String,Object>m=new LinkedHashMap<>();m.put("id",u.getId());m.put("username",u.getUsername());m.put("nickname",u.getNickname());m.put("avatar",u.getAvatarUrl());m.put("email",u.getEmail());m.put("phone",u.getPhone());m.put("role",u.getRole().name());m.put("status",u.getStatus().name());m.put("certified",views.bool("SELECT COUNT(*)>0 FROM creator_profiles WHERE user_id=? AND auth_status='CERTIFIED'",u.getId()));m.put("videoCount",views.count("SELECT COUNT(*) FROM videos WHERE user_id=?",u.getId()));m.put("createdAt",u.getCreatedAt());m.put("lastLoginAt",u.getLastLoginAt());return m;}).toList();return page(all,page,size);}
    @Transactional public Map<String,Object> status(long operator,long id,UserStatus status,String reason){User u=user(id);u.changeStatus(status);audit(operator,"USER_STATUS","USER",id,Map.of("status",status.name(),"reason",Objects.toString(reason,"")));return Map.of("success",true,"status",status.name());}
    @Transactional public Map<String,Object> role(long operator,long id,Role role){User u=user(id);u.changeRole(role);audit(operator,"ROLE_ASSIGN","USER",id,Map.of("role",role.name()));return Map.of("success",true,"role",role.name());}
    public Map<String,Object> videos(String status,int page,int size){List<Map<String,Object>> all=videos.findAll().stream().filter(v->status==null||status.equals("ALL")||v.getStatus().name().equals(status)).map(v->views.videoSummary(v,null)).toList();return page(all,page,size);}
    public Map<String,Object> auditLogs(int page,int size){List<Map<String,Object>> all=jdbc.query("SELECT * FROM admin_audit_log ORDER BY created_at DESC",(rs,n)->{Map<String,Object>m=new LinkedHashMap<>();m.put("id",rs.getLong("id"));m.put("operator",views.brief(rs.getLong("operator_id")));m.put("action",rs.getString("action"));m.put("targetType",rs.getString("target_type"));m.put("targetId",rs.getLong("target_id"));try{m.put("detail",json.readValue(Objects.requireNonNullElse(rs.getString("detail"),"{}"),new TypeReference<Map<String,Object>>(){}));}catch(Exception e){m.put("detail",Map.of());}m.put("createdAt",rs.getTimestamp("created_at").toInstant());return m;});return page(all,page,size);}
    public Map<String,Object> settings(){List<String> rows=jdbc.query("SELECT setting_value FROM platform_settings WHERE setting_key='platform'",(rs,n)->rs.getString(1));if(rows.isEmpty())return defaults();try{return json.readValue(rows.get(0),new TypeReference<Map<String,Object>>(){});}catch(Exception ex){return defaults();}}
    @Transactional public Map<String,Object> settings(long operator,Map<String,Object> value){try{String text=json.writeValueAsString(value);int updated=jdbc.update("UPDATE platform_settings SET setting_value=?,updated_by=?,updated_at=? WHERE setting_key='platform'",text,operator,Timestamp.from(Instant.now()));if(updated==0)jdbc.update("INSERT INTO platform_settings(setting_key,setting_value,updated_by) VALUES(?,?,?)","platform",text,operator);audit(operator,"SETTINGS_UPDATE","PLATFORM",0,Map.of("changed",true));return value;}catch(Exception ex){throw new ApiException(ErrorCode.VALIDATION,"设置格式错误");}}
    private Map<String,Object> defaults(){Map<String,Object>m=new LinkedHashMap<>();m.put("review",Map.of("newUserForceReview",true,"newUserWindowHours",24,"highTrustSampleRate",.1,"autoReportThreshold",3));m.put("upload",Map.of("longMaxSizeGB",8,"shortMaxSizeMB",500,"longMaxDurationHours",4,"shortMaxDurationSeconds",180,"allowedExtensions",List.of("mp4","mov","webm","m4v")));m.put("recommend",Map.of("personalizationEnabled",true,"hotFallback",true));m.put("minor",Map.of("teenagerModeEnabled",true,"dailyLimitMinutes",40,"nightBlockStart","22:00","nightBlockEnd","06:00"));return m;}
    private void audit(long operator,String action,String type,long target,Map<String,Object>detail){try{Map<String,Object>v=new HashMap<>();v.put("operator_id",operator);v.put("action",action);v.put("target_type",type);v.put("target_id",target);v.put("detail",json.writeValueAsString(detail));new SimpleJdbcInsert(jdbc).withTableName("admin_audit_log").usingColumns("operator_id","action","target_type","target_id","detail").execute(v);}catch(Exception ignored){}}
    private User user(long id){return users.findById(id).orElseThrow(()->new ApiException(ErrorCode.NOT_FOUND,"用户不存在"));}private Long nullable(ResultSet rs,String name)throws SQLException{long v=rs.getLong(name);return rs.wasNull()?null:v;}
    private Map<String,Object> page(List<?>all,int page,int size){page=Math.max(1,page);size=Math.max(1,Math.min(size,100));int from=(int)Math.min((long)(page-1)*size,all.size()),to=Math.min(from+size,all.size());Map<String,Object>m=new LinkedHashMap<>();m.put("items",all.subList(from,to));m.put("total",all.size());m.put("page",page);m.put("pageSize",size);m.put("hasMore",to<all.size());return m;}
}
