package com.videoshare.feed;

import com.videoshare.auth.CurrentUser;import com.videoshare.common.*;import com.videoshare.realtime.RealtimeNotifier;import com.videoshare.user.UserRepository;import java.sql.*;import java.time.*;import java.util.*;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.jdbc.core.simple.SimpleJdbcInsert;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;

@Service
public class SocialService {
    private final JdbcTemplate jdbc;private final ViewFactory views;private final UserRepository users;private final RealtimeNotifier notifier;
    public SocialService(JdbcTemplate jdbc,ViewFactory views,UserRepository users,RealtimeNotifier notifier){this.jdbc=jdbc;this.views=views;this.users=users;this.notifier=notifier;}
    public Map<String,Object> feeds(String type,String cursor,int size,Long viewer,Long onlyUser){size=Math.max(1,Math.min(size,100));int offset=parse(cursor);String sql="SELECT * FROM feeds WHERE status='VISIBLE'"+(onlyUser!=null?" AND user_id=?":"")+" ORDER BY "+("hot".equals(type)?"like_count DESC,":"")+"created_at DESC";List<Map<String,Object>> all=onlyUser==null?jdbc.query(sql,(rs,n)->feed(rs,viewer)):jdbc.query(sql,(rs,n)->feed(rs,viewer),onlyUser);if("following".equals(type)){if(viewer==null)throw new ApiException(ErrorCode.UNAUTHORIZED,"请先登录");all=all.stream().filter(f->views.bool("SELECT COUNT(*)>0 FROM follows WHERE follower_id=? AND followee_id=?",viewer,((Map<?,?>)f.get("user")).get("id"))).toList();}int to=(int)Math.min((long)offset+size,all.size());Map<String,Object> m=new LinkedHashMap<>();m.put("items",all.subList(Math.min(offset,to),to));m.put("total",all.size());m.put("nextCursor",to<all.size()?String.valueOf(to):null);m.put("hasMore",to<all.size());return m;}
    public Map<String,Object> feed(long id,Long viewer){List<Map<String,Object>> rows=jdbc.query("SELECT * FROM feeds WHERE id=? AND status='VISIBLE'",(rs,n)->feed(rs,viewer),id);if(rows.isEmpty())throw new ApiException(ErrorCode.NOT_FOUND,"动态不存在");return rows.get(0);}
    @Transactional public Map<String,Object> publish(long userId,Map<String,Object> body){String content=Objects.toString(body.get("content"),"").replaceAll("<[^>]*>","").trim();if(content.isBlank()||content.length()>2000)throw new ApiException(ErrorCode.VALIDATION,"动态内容应为 1-2000 字");Long topicId=null;String topic=Objects.toString(body.get("topicName"),"").trim();if(!topic.isBlank()){List<Long> existing=jdbc.query("SELECT id FROM topics WHERE name=?",(rs,n)->rs.getLong(1),topic);if(existing.isEmpty())topicId=new SimpleJdbcInsert(jdbc).withTableName("topics").usingGeneratedKeyColumns("id").usingColumns("name","view_count").executeAndReturnKey(Map.of("name",topic,"view_count",0)).longValue();else topicId=existing.get(0);}Long repost=body.get("repostOfId")instanceof Number n?n.longValue():null;if(repost!=null){Map<String,Object> original=feed(repost,userId);if(original.get("repostOf")instanceof Map<?,?> root)repost=((Number)root.get("id")).longValue();jdbc.update("UPDATE feeds SET repost_count=repost_count+1 WHERE id=?",repost);}Map<String,Object> values=new HashMap<>();values.put("user_id",userId);values.put("content",content);values.put("type",repost==null?"ORIGINAL":"REPOST");values.put("repost_of_id",repost);values.put("topic_id",topicId);values.put("status","VISIBLE");long id=new SimpleJdbcInsert(jdbc).withTableName("feeds").usingGeneratedKeyColumns("id").usingColumns("user_id","content","type","repost_of_id","topic_id","status").executeAndReturnKey(values).longValue();if(body.get("media")instanceof List<?> list){int order=0;for(Object item:list)if(item instanceof Map<?,?> media){Map<String,Object> mv=new HashMap<>();mv.put("feed_id",id);mv.put("media_type",Objects.toString(media.get("mediaType"),"IMAGE"));mv.put("url",Objects.toString(media.get("url"),""));mv.put("thumb_url",media.get("thumbUrl"));mv.put("video_id",media.get("videoId"));mv.put("sort_order",order++);new SimpleJdbcInsert(jdbc).withTableName("feed_media").usingColumns("feed_id","media_type","url","thumb_url","video_id","sort_order").execute(mv);}}return feed(id,userId);}
    @Transactional public void remove(long userId,long id,boolean admin){Map<String,Object> row=jdbc.queryForMap("SELECT user_id FROM feeds WHERE id=?",id);if(((Number)row.get("user_id")).longValue()!=userId&&!admin)throw new ApiException(ErrorCode.FORBIDDEN,"不能删除他人的动态");jdbc.update("UPDATE feeds SET status='DELETED' WHERE id=?",id);}
    @Transactional public Map<String,Object> like(long userId,long id,boolean active){feed(id,userId);boolean exists=views.liked(userId,"FEED",id,"LIKE");if(active&&!exists){jdbc.update("INSERT INTO likes(user_id,target_type,target_id,type) VALUES(?,?,?,?)",userId,"FEED",id,"LIKE");long owner=jdbc.queryForObject("SELECT user_id FROM feeds WHERE id=?",Long.class,id);notifier.notify(owner,userId,"LIKE","动态获得点赞","有人赞了你的动态","FEED",id);}if(!active&&exists)jdbc.update("DELETE FROM likes WHERE user_id=? AND target_type='FEED' AND target_id=?",userId,id);long count=views.count("SELECT COUNT(*) FROM likes WHERE target_type='FEED' AND target_id=?",id);jdbc.update("UPDATE feeds SET like_count=? WHERE id=?",count,id);return Map.of("active",active,"count",count);}
    @Transactional public long repost(long userId,long id){Map<String,Object> original=feed(id,userId);publish(userId,Map.of("content","转发动态","repostOfId",id));return views.count("SELECT repost_count FROM feeds WHERE id=?",id);}
    public Map<String,Object> comments(long feedId,int page,int size,Long viewer){feed(feedId,viewer);List<Map<String,Object>> all=jdbc.query("SELECT * FROM feed_comments WHERE feed_id=? AND status='VISIBLE' ORDER BY created_at DESC",(rs,n)->feedComment(rs,viewer),feedId);return page(all,page,size);}
    @Transactional public Map<String,Object> comment(long userId,long feedId,String content){feed(feedId,userId);if(content==null||content.isBlank()||content.length()>1000)throw new ApiException(ErrorCode.VALIDATION,"评论长度应为 1-1000 字");Map<String,Object> values=new HashMap<>();values.put("feed_id",feedId);values.put("user_id",userId);values.put("content",content.replaceAll("<[^>]*>","").trim());values.put("status","VISIBLE");long id=new SimpleJdbcInsert(jdbc).withTableName("feed_comments").usingGeneratedKeyColumns("id").usingColumns("feed_id","user_id","content","status").executeAndReturnKey(values).longValue();jdbc.update("UPDATE feeds SET comment_count=comment_count+1 WHERE id=?",feedId);long owner=jdbc.queryForObject("SELECT user_id FROM feeds WHERE id=?",Long.class,feedId);notifier.notify(owner,userId,"COMMENT","动态收到评论",content.replaceAll("<[^>]*>","").trim(),"FEED",feedId);return jdbc.query("SELECT * FROM feed_comments WHERE id=?",(rs,n)->feedComment(rs,userId),id).get(0);}
    @Transactional public Map<String,Object> report(long userId,Map<String,Object> body){String reason=Objects.toString(body.get("reason"),"");if(reason.isBlank())throw new ApiException(ErrorCode.VALIDATION,"请选择举报类型");Map<String,Object> v=new HashMap<>();v.put("reporter_id",userId);v.put("target_type",Objects.toString(body.get("targetType"),"VIDEO"));v.put("target_id",((Number)body.getOrDefault("targetId",0)).longValue());v.put("reason",reason);v.put("description",Objects.toString(body.get("description"),""));v.put("evidence_urls",String.valueOf(body.getOrDefault("evidenceUrls",List.of())));v.put("target_snapshot","提交时内容快照");v.put("priority","ILLEGAL".equals(reason)?100:10);v.put("status","PENDING");long id=new SimpleJdbcInsert(jdbc).withTableName("reports").usingGeneratedKeyColumns("id").usingColumns("reporter_id","target_type","target_id","reason","description","evidence_urls","target_snapshot","priority","status").executeAndReturnKey(v).longValue();return Map.of("reportId",id,"status","PENDING");}
    public Map<String,Object> notifications(long userId,String type,int page,int size){String sql="SELECT * FROM notifications WHERE user_id=?"+(type!=null&&!type.equals("ALL")?" AND type=?":"")+" ORDER BY created_at DESC";List<Map<String,Object>> all=type!=null&&!type.equals("ALL")?jdbc.query(sql,(rs,n)->notification(rs),userId,type):jdbc.query(sql,(rs,n)->notification(rs),userId);Map<String,Object> result=new LinkedHashMap<>(page(all,page,size));result.put("unreadCount",views.count("SELECT COUNT(*) FROM notifications WHERE user_id=? AND is_read=FALSE",userId));return result;}
    @Transactional public void readNotifications(long userId,List<?> ids){if(ids==null||ids.isEmpty())jdbc.update("UPDATE notifications SET is_read=TRUE WHERE user_id=?",userId);else for(Object id:ids)if(id instanceof Number n)jdbc.update("UPDATE notifications SET is_read=TRUE WHERE user_id=? AND id=?",userId,n.longValue());}
    public List<Map<String,Object>> conversations(long userId){return jdbc.query("SELECT * FROM conversations WHERE user_a_id=? OR user_b_id=? ORDER BY updated_at DESC",(rs,n)->{long peer=rs.getLong("user_a_id")==userId?rs.getLong("user_b_id"):rs.getLong("user_a_id");long id=rs.getLong("id");Map<String,Object>m=new LinkedHashMap<>();m.put("id",id);m.put("peer",views.brief(peer));List<String> last=jdbc.query("SELECT content FROM direct_messages WHERE conversation_id=? ORDER BY created_at DESC LIMIT 1",(r,i)->r.getString(1),id);m.put("lastMessage",last.isEmpty()?"":last.get(0));m.put("lastMessageAt",rs.getTimestamp("updated_at").toInstant());m.put("unreadCount",views.count("SELECT COUNT(*) FROM direct_messages WHERE conversation_id=? AND sender_id<>? AND is_read=FALSE",id,userId));return m;},userId,userId);}
    @Transactional public List<Map<String,Object>> messages(long userId,long conversationId){ownConversation(userId,conversationId);jdbc.update("UPDATE direct_messages SET is_read=TRUE WHERE conversation_id=? AND sender_id<>?",conversationId,userId);return jdbc.query("SELECT * FROM direct_messages WHERE conversation_id=? ORDER BY created_at,id",(rs,n)->message(rs,userId),conversationId);}
    @Transactional public Map<String,Object> sendMessage(long userId,long conversationId,Map<String,Object> body){ownConversation(userId,conversationId);String content=Objects.toString(body.get("content"),"").trim();if(content.isBlank())throw new ApiException(ErrorCode.VALIDATION,"消息不能为空");Map<String,Object>v=new HashMap<>();v.put("conversation_id",conversationId);v.put("sender_id",userId);v.put("content",content);v.put("is_read",false);long id=new SimpleJdbcInsert(jdbc).withTableName("direct_messages").usingGeneratedKeyColumns("id").usingColumns("conversation_id","sender_id","content","is_read").executeAndReturnKey(v).longValue();jdbc.update("UPDATE conversations SET updated_at=? WHERE id=?",Timestamp.from(Instant.now()),conversationId);Map<String,Object>conversation=jdbc.queryForMap("SELECT user_a_id,user_b_id FROM conversations WHERE id=?",conversationId);long userA=((Number)conversation.get("user_a_id")).longValue(),userB=((Number)conversation.get("user_b_id")).longValue();long peer=userA==userId?userB:userA;notifier.notify(peer,userId,"SYSTEM","收到新私信",content.length()>80?content.substring(0,80)+"…":content,"USER",userId);return jdbc.query("SELECT * FROM direct_messages WHERE id=?",(rs,n)->message(rs,userId),id).get(0);}
    private Map<String,Object> feed(ResultSet rs,Long viewer)throws SQLException{long id=rs.getLong("id"),userId=rs.getLong("user_id");Map<String,Object>m=new LinkedHashMap<>();m.put("id",id);m.put("type",rs.getString("type"));m.put("content",rs.getString("content"));m.put("user",views.brief(userId));m.put("media",jdbc.query("SELECT * FROM feed_media WHERE feed_id=? ORDER BY sort_order",(r,n)->{Map<String,Object>x=new LinkedHashMap<>();x.put("id",r.getLong("id"));x.put("mediaType",r.getString("media_type"));x.put("url",r.getString("url"));x.put("thumbUrl",r.getString("thumb_url"));x.put("videoId",nullable(r,"video_id"));x.put("sortOrder",r.getInt("sort_order"));return x;},id));Long topic=nullable(rs,"topic_id");m.put("topic",topic==null?null:jdbc.queryForMap("SELECT id,name FROM topics WHERE id=?",topic));m.put("mentions",List.of());Long repost=nullable(rs,"repost_of_id");m.put("repostOf",repost==null?null:repostPreview(repost,viewer));m.put("stats",Map.of("likes",rs.getLong("like_count"),"comments",rs.getLong("comment_count"),"reposts",rs.getLong("repost_count")));m.put("liked",viewer!=null&&views.liked(viewer,"FEED",id,"LIKE"));m.put("createdAt",rs.getTimestamp("created_at").toInstant());m.put("isOwner",viewer!=null&&viewer==userId);return m;}
    private Map<String,Object> repostPreview(long id,Long viewer){List<Map<String,Object>> rows=jdbc.query("SELECT * FROM feeds WHERE id=? AND status=\'VISIBLE\'",(rs,n)->feed(rs,viewer),id);return rows.isEmpty()?null:rows.get(0);}
    private Map<String,Object> feedComment(ResultSet rs,Long viewer)throws SQLException{long id=rs.getLong("id"),user=rs.getLong("user_id"),feed=rs.getLong("feed_id");Map<String,Object>m=new LinkedHashMap<>();m.put("id",id);m.put("videoId",feed);m.put("parentId",null);m.put("rootId",null);m.put("content",rs.getString("content"));m.put("user",views.brief(user));m.put("likeCount",0);m.put("replyCount",0);m.put("liked",false);m.put("status",rs.getString("status"));m.put("createdAt",rs.getTimestamp("created_at").toInstant());return m;}
    private Map<String,Object> notification(ResultSet rs)throws SQLException{Map<String,Object>m=new LinkedHashMap<>();m.put("id",rs.getLong("id"));m.put("type",rs.getString("type"));m.put("title",rs.getString("title"));m.put("content",rs.getString("content"));Long actor=nullable(rs,"actor_id");m.put("actor",actor==null?null:views.brief(actor));m.put("targetType",rs.getString("target_type"));m.put("targetId",nullable(rs,"target_id"));m.put("isRead",rs.getBoolean("is_read"));m.put("createdAt",rs.getTimestamp("created_at").toInstant());return m;}
    private Map<String,Object> message(ResultSet rs,long viewer)throws SQLException{Map<String,Object>m=new LinkedHashMap<>();m.put("id",rs.getLong("id"));m.put("conversationId",rs.getLong("conversation_id"));m.put("senderId",rs.getLong("sender_id"));m.put("content",rs.getString("content"));m.put("attachment",null);m.put("createdAt",rs.getTimestamp("created_at").toInstant());m.put("mine",rs.getLong("sender_id")==viewer);return m;}
    private void ownConversation(long userId,long id){if(!views.bool("SELECT COUNT(*)>0 FROM conversations WHERE id=? AND (user_a_id=? OR user_b_id=?)",id,userId,userId))throw new ApiException(ErrorCode.FORBIDDEN,"无权访问该会话");}
    private Long nullable(ResultSet rs,String name)throws SQLException{long v=rs.getLong(name);return rs.wasNull()?null:v;}private int parse(String c){try{return c==null?0:Math.max(0,Integer.parseInt(c));}catch(Exception e){return 0;}}
    private Map<String,Object> page(List<?> all,int page,int size){page=Math.max(1,page);size=Math.max(1,Math.min(size,100));int from=(int)Math.min((long)(page-1)*size,all.size()),to=Math.min(from+size,all.size());Map<String,Object>m=new LinkedHashMap<>();m.put("items",all.subList(from,to));m.put("total",all.size());m.put("page",page);m.put("pageSize",size);m.put("hasMore",to<all.size());return m;}
}
