package com.videoshare.video;

import com.videoshare.auth.CurrentUser; import com.videoshare.common.ApiResponse; import com.videoshare.media.FileAsset; import com.videoshare.media.FileAssetRepository; import com.videoshare.media.StorageGateway; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import java.io.InputStream; import java.util.regex.Matcher; import java.util.regex.Pattern; import org.springframework.http.*; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.web.bind.annotation.*; import org.springframework.web.servlet.mvc.method.annotation.StreamingResponseBody;

@RestController @RequestMapping("/api/v1/videos")
public class VideoController {
    private static final Pattern RANGE=Pattern.compile("bytes=(\\d+)-(\\d*)");
    private final VideoService service; private final FileAssetRepository files; private final StorageGateway storage;
    public VideoController(VideoService service,FileAssetRepository files,StorageGateway storage){this.service=service;this.files=files;this.storage=storage;}
    @GetMapping("/{id}") public ApiResponse<java.util.Map<String,Object>> detail(@PathVariable long id,@AuthenticationPrincipal CurrentUser current){return ApiResponse.ok(service.detail(id,current));}
    @GetMapping("/{id}/source") public ResponseEntity<StreamingResponseBody> source(@PathVariable long id,@AuthenticationPrincipal CurrentUser current,@RequestHeader(value="Range",required=false)String range){Video video=service.playable(id,current);FileAsset file=files.findById(video.getSourceFileId()).orElseThrow(()->new com.videoshare.common.ApiException(com.videoshare.common.ErrorCode.NOT_FOUND,"视频文件不存在"));long total=file.getFileSize();long start=0,end=total-1;boolean partial=range!=null&&!range.isBlank();if(partial){Matcher matcher=RANGE.matcher(range);if(!matcher.matches())return ResponseEntity.status(HttpStatus.REQUESTED_RANGE_NOT_SATISFIABLE).header(HttpHeaders.CONTENT_RANGE,"bytes */"+total).build();start=Long.parseLong(matcher.group(1));if(matcher.group(2)!=null&&!matcher.group(2).isBlank())end=Long.parseLong(matcher.group(2));end=Math.min(end,total-1);if(start> end||start>=total)return ResponseEntity.status(HttpStatus.REQUESTED_RANGE_NOT_SATISFIABLE).header(HttpHeaders.CONTENT_RANGE,"bytes */"+total).build();}long length=end-start+1;StorageGateway.StoredObject object=storage.open(file.getBucket(),file.getObjectKey(),start,length);StreamingResponseBody body=output->{try(InputStream input=object.stream()){input.transferTo(output);}};HttpHeaders headers=new HttpHeaders();headers.set(HttpHeaders.ACCEPT_RANGES,"bytes");headers.setContentLength(length);headers.setContentType(MediaType.parseMediaType(file.getMimeType()));if(partial)headers.set(HttpHeaders.CONTENT_RANGE,"bytes "+start+"-"+end+"/"+total);return new ResponseEntity<>(body,headers,partial?HttpStatus.PARTIAL_CONTENT:HttpStatus.OK);}
    @GetMapping("/recommend") public ApiResponse<VideoDtos.PageData<java.util.Map<String,Object>>> discover(@RequestParam(required=false) String q,@RequestParam(required=false) VideoType videoType,@RequestParam(required=false) Long categoryId,@RequestParam(defaultValue="recommend") String sort,@RequestParam(defaultValue="1") @Min(1) int page,@RequestParam(defaultValue="20") @Min(1) @Max(100) int pageSize,@AuthenticationPrincipal CurrentUser current){return ApiResponse.ok(service.discover(q,videoType,categoryId,sort,page,pageSize,current));}
    @GetMapping("/search") public ApiResponse<java.util.Map<String,Object>> search(@RequestParam @NotBlank String q,@RequestParam(required=false) String duration,@RequestParam(required=false) String dateRange,@RequestParam(required=false) Long categoryId,@RequestParam(defaultValue="relevance") String sort,@RequestParam(defaultValue="1") @Min(1) int page,@RequestParam(defaultValue="20") @Min(1) @Max(100) int pageSize,@AuthenticationPrincipal CurrentUser current){var data=service.discover(q,null,categoryId,sort,page,pageSize,current,duration,dateRange);var result=new java.util.LinkedHashMap<String,Object>();result.put("items",data.items());result.put("total",data.total());result.put("page",data.page());result.put("pageSize",data.pageSize());result.put("hasMore",data.hasMore());result.put("suggestions",java.util.List.of("架构设计","性能优化","旅行","美食"));result.put("costMs",1);return ApiResponse.ok(result);}
    @PutMapping("/{id}") public ApiResponse<java.util.Map<String,Object>> edit(@PathVariable long id,@AuthenticationPrincipal CurrentUser current,@Valid @RequestBody VideoDtos.EditRequest request){return ApiResponse.ok(service.edit(id,current,request));}
    @DeleteMapping("/{id}") public ApiResponse<java.util.Map<String,Object>> delete(@PathVariable long id,@AuthenticationPrincipal CurrentUser current){service.delete(id,current);return ApiResponse.ok(java.util.Map.of("success",true,"recoverableUntil",java.time.Instant.now().plus(java.time.Duration.ofDays(30))));}
}
