package com.videoshare.video;

import com.videoshare.auth.CurrentUser; import com.videoshare.common.ApiResponse; import jakarta.validation.Valid; import jakarta.validation.constraints.*; import org.springframework.security.core.annotation.AuthenticationPrincipal; import org.springframework.web.bind.annotation.*;

@RestController @RequestMapping("/api/v1/videos")
public class VideoController {
    private final VideoService service; public VideoController(VideoService service){this.service=service;}
    @GetMapping("/{id}") public ApiResponse<java.util.Map<String,Object>> detail(@PathVariable long id,@AuthenticationPrincipal CurrentUser current){return ApiResponse.ok(service.detail(id,current));}
    @GetMapping("/recommend") public ApiResponse<VideoDtos.PageData<java.util.Map<String,Object>>> discover(@RequestParam(required=false) String q,@RequestParam(required=false) VideoType videoType,@RequestParam(required=false) Long categoryId,@RequestParam(defaultValue="recommend") String sort,@RequestParam(defaultValue="1") @Min(1) int page,@RequestParam(defaultValue="20") @Min(1) @Max(100) int pageSize,@AuthenticationPrincipal CurrentUser current){return ApiResponse.ok(service.discover(q,videoType,categoryId,sort,page,pageSize,current));}
    @GetMapping("/search") public ApiResponse<java.util.Map<String,Object>> search(@RequestParam @NotBlank String q,@RequestParam(required=false) Long categoryId,@RequestParam(defaultValue="relevance") String sort,@RequestParam(defaultValue="1") @Min(1) int page,@RequestParam(defaultValue="20") @Min(1) @Max(100) int pageSize,@AuthenticationPrincipal CurrentUser current){var data=service.discover(q,null,categoryId,sort,page,pageSize,current);var result=new java.util.LinkedHashMap<String,Object>();result.put("items",data.items());result.put("total",data.total());result.put("page",data.page());result.put("pageSize",data.pageSize());result.put("hasMore",data.hasMore());result.put("suggestions",java.util.List.of("架构设计","性能优化","旅行","美食"));result.put("costMs",1);return ApiResponse.ok(result);}
    @PutMapping("/{id}") public ApiResponse<java.util.Map<String,Object>> edit(@PathVariable long id,@AuthenticationPrincipal CurrentUser current,@Valid @RequestBody VideoDtos.EditRequest request){return ApiResponse.ok(service.edit(id,current,request));}
    @DeleteMapping("/{id}") public ApiResponse<java.util.Map<String,Object>> delete(@PathVariable long id,@AuthenticationPrincipal CurrentUser current){service.delete(id,current);return ApiResponse.ok(java.util.Map.of("success",true,"recoverableUntil",java.time.Instant.now().plus(java.time.Duration.ofDays(30))));}
}
