package com.videoshare.video;

import com.videoshare.auth.CurrentUser; import com.videoshare.common.*;
import jakarta.persistence.criteria.Predicate;
import java.util.*; import org.springframework.data.domain.*; import org.springframework.data.jpa.domain.Specification; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;

@Service
public class VideoService {
    private final VideoRepository videos; private final ViewFactory views; private final JdbcTemplate jdbc;
    public VideoService(VideoRepository videos,ViewFactory views,JdbcTemplate jdbc){this.videos=videos;this.views=views;this.jdbc=jdbc;}
    @Transactional(readOnly=true) public Map<String,Object> detail(long id,CurrentUser current) { Video video=accessible(id,current); return views.videoDetail(video,current==null?null:current.id()); }
    @Transactional(readOnly=true) public VideoDtos.PageData<Map<String,Object>> discover(String query,VideoType type,Long categoryId,String sort,int page,int size,CurrentUser current) { Sort sorting=switch(Objects.requireNonNullElse(sort,"recommend")){case "views"->Sort.by(Sort.Direction.DESC,"viewCount");case "latest"->Sort.by(Sort.Direction.DESC,"publishedAt");default->Sort.by(Sort.Direction.DESC,"likeCount").and(Sort.by(Sort.Direction.DESC,"publishedAt"));};Specification<Video> spec=(root,q,cb)->{List<Predicate> p=new ArrayList<>();p.add(cb.equal(root.get("status"),VideoStatus.PUBLISHED));p.add(cb.equal(root.get("visibility"),Visibility.PUBLIC));if(query!=null&&!query.isBlank())p.add(cb.like(cb.lower(root.get("title")),"%"+query.trim().toLowerCase()+"%"));if(type!=null)p.add(cb.equal(root.get("videoType"),type));if(categoryId!=null)p.add(cb.equal(root.get("categoryId"),categoryId));return cb.and(p.toArray(Predicate[]::new));};Page<Video> result=videos.findAll(spec,PageRequest.of(page-1,size,sorting));Long viewer=current==null?null:current.id();return new VideoDtos.PageData<>(result.stream().map(v->views.videoSummary(v,viewer)).toList(),result.getTotalElements(),page,size,result.hasNext()); }
    @Transactional public Map<String,Object> edit(long id,CurrentUser current,VideoDtos.EditRequest request) { Video video=videos.findById(id).orElseThrow(()->new ApiException(ErrorCode.NOT_FOUND,"视频不存在")); owner(video,current); video.editPartial(request.title(),request.description(),request.categoryId(),request.visibility(),request.downloadEnabled());if(request.tags()!=null){jdbc.update("DELETE FROM video_tags WHERE video_id=?",id);for(String rawTag:request.tags()){String tag=rawTag==null?"":rawTag.trim();if(tag.isBlank())continue;List<Long>tagIds=jdbc.query("SELECT id FROM tags WHERE tag_name=?",(rs,n)->rs.getLong(1),tag);Long tagId=tagIds.isEmpty()?insertTag(tag):tagIds.get(0);jdbc.update("INSERT INTO video_tags(video_id,tag_id) VALUES(?,?)",id,tagId);}} return views.videoDetail(video,current.id()); }
    @Transactional public void delete(long id,CurrentUser current) { Video video=videos.findById(id).orElseThrow(()->new ApiException(ErrorCode.NOT_FOUND,"视频不存在")); owner(video,current); video.delete(); }
    private Video accessible(long id,CurrentUser current) { Video v=videos.findById(id).orElseThrow(()->new ApiException(ErrorCode.NOT_FOUND,"视频不存在"));boolean privileged=current!=null&&(current.id()==v.getUserId()||current.role()==com.videoshare.user.Role.ADMIN||current.role()==com.videoshare.user.Role.MODERATOR);if(!privileged&&(v.getStatus()!=VideoStatus.PUBLISHED||v.getVisibility()!=Visibility.PUBLIC))throw new ApiException(ErrorCode.NOT_FOUND,"视频不存在");return v; }
    private void owner(Video video,CurrentUser current) { if(current==null) throw new ApiException(ErrorCode.UNAUTHORIZED,"请先登录"); if(video.getUserId()!=current.id() && current.role()!=com.videoshare.user.Role.ADMIN) throw new ApiException(ErrorCode.FORBIDDEN,"不能操作其他用户的视频"); }
    private Long insertTag(String tag){jdbc.update("INSERT INTO tags(tag_name) VALUES(?)",tag);return jdbc.queryForObject("SELECT id FROM tags WHERE tag_name=?",Long.class,tag);}
}
