package com.videoshare.user;

import com.videoshare.auth.*;
import com.videoshare.common.*;
import com.videoshare.video.*;
import java.sql.*;
import java.time.*;
import java.util.*;
import org.springframework.data.domain.Sort;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class UserApiService {
    private final UserRepository users;private final VideoRepository videos;private final ViewFactory views;private final JdbcTemplate jdbc;private final PasswordEncoder encoder;private final SensitiveDataCipher cipher;private final AccountLifecycleService lifecycle;
    public UserApiService(UserRepository users,VideoRepository videos,ViewFactory views,JdbcTemplate jdbc,PasswordEncoder encoder,SensitiveDataCipher cipher,AccountLifecycleService lifecycle){this.users=users;this.videos=videos;this.views=views;this.jdbc=jdbc;this.encoder=encoder;this.cipher=cipher;this.lifecycle=lifecycle;}
    public Map<String,Object> profile(long id,CurrentUser current){return views.profile(id,current==null?null:current.id(),current!=null&&current.id()==id);}
    @Transactional public Map<String,Object> update(long id,Map<String,Object> body){User u=user(id);u.updateProfile(string(body,"nickname"),string(body,"bio"),string(body,"avatar"));return views.profile(id,id,true);}
    @Transactional public void password(long id,String oldPassword,String newPassword){User u=user(id);if(!encoder.matches(oldPassword,u.getPasswordHash()))throw new ApiException(ErrorCode.VALIDATION,"原密码不正确");if(newPassword==null||newPassword.length()<8)throw new ApiException(ErrorCode.VALIDATION,"新密码至少 8 位");u.changePassword(encoder.encode(newPassword));}
    @Transactional public String realName(long id,String realName,String idCard){if(realName==null||realName.isBlank()||idCard==null||idCard.length()<15)throw new ApiException(ErrorCode.VALIDATION,"实名信息不完整");jdbc.update("UPDATE creator_profiles SET real_name_encrypted=?,id_card_hash=?,auth_status='PENDING' WHERE user_id=?",cipher.encrypt(realName),sha256(idCard),id);return "PENDING";}
    @Transactional public Map<String,Object> deactivate(long id,String reason){user(id);return Map.of("scheduledAt",lifecycle.requestDeletion(id,reason),"coolDownDays",7);}
    public Map<String,Object> videos(long userId,int page,int size,Long viewer){List<Video> list=videos.findAll().stream().filter(v->v.getUserId()==userId&&v.getStatus()==VideoStatus.PUBLISHED&&v.getVisibility()==Visibility.PUBLIC).sorted(Comparator.comparing(Video::getPublishedAt,Comparator.nullsLast(Comparator.reverseOrder()))).toList();return page(list.stream().map(v->views.videoSummary(v,viewer)).toList(),page,size);}
    public Map<String,Object> favorites(long userId,int page,int size,Long viewer){List<Long> ids=jdbc.query("SELECT video_id FROM favorites WHERE user_id=? ORDER BY created_at DESC",(rs,n)->rs.getLong(1),userId);List<Map<String,Object>> list=ids.stream().map(videos::findById).flatMap(Optional::stream).filter(v->v.getStatus()==VideoStatus.PUBLISHED&&v.getVisibility()==Visibility.PUBLIC).map(v->views.videoSummary(v,viewer)).toList();return page(list,page,size);}
    public Map<String,Object> follows(long userId,boolean followers,int page,int size,Long viewer){String sql=followers?"SELECT follower_id,created_at FROM follows WHERE followee_id=? ORDER BY created_at DESC":"SELECT followee_id,created_at FROM follows WHERE follower_id=? ORDER BY created_at DESC";List<Map<String,Object>> list=jdbc.query(sql,(rs,n)->{long id=rs.getLong(1);Map<String,Object> m=new LinkedHashMap<>(views.brief(id));boolean followed=viewer!=null&&views.bool("SELECT COUNT(*)>0 FROM follows WHERE follower_id=? AND followee_id=?",viewer,id);m.put("followed",followed);m.put("mutual",followed&&viewer!=null&&views.bool("SELECT COUNT(*)>0 FROM follows WHERE follower_id=? AND followee_id=?",id,viewer));m.put("followedAt",rs.getTimestamp(2).toInstant());return m;},userId);return page(list,page,size);}
    @Transactional public Map<String,Object> follow(long viewer,long target,boolean active){if(viewer==target)throw new ApiException(ErrorCode.VALIDATION,"不能关注自己");user(target);int exists=jdbc.queryForObject("SELECT COUNT(*) FROM follows WHERE follower_id=? AND followee_id=?",Integer.class,viewer,target);if(active&&exists==0)jdbc.update("INSERT INTO follows(follower_id,followee_id) VALUES(?,?)",viewer,target);if(!active&&exists>0)jdbc.update("DELETE FROM follows WHERE follower_id=? AND followee_id=?",viewer,target);boolean mutual=active&&views.bool("SELECT COUNT(*)>0 FROM follows WHERE follower_id=? AND followee_id=?",target,viewer);return Map.of("active",active,"mutual",mutual);}
    public List<Map<String,Object>> suggested(Long viewer){return users.findAll(Sort.by("id")).stream().filter(u->viewer==null||u.getId()!=viewer).limit(8).map(u->{Map<String,Object> m=new LinkedHashMap<>(views.brief(u.getId()));m.put("reason","活跃创作者");return m;}).toList();}
    public Map<String,Object> creatorVideos(long userId,String status,int page,int size){List<Map<String,Object>> list=videos.findAll().stream().filter(v->v.getUserId()==userId&&(status==null||status.equals("ALL")||v.getStatus().name().equals(status))).sorted(Comparator.comparing(Video::getCreatedAt).reversed()).map(v->{Map<String,Object> m=new LinkedHashMap<>(views.videoSummary(v,userId));m.put("transcodeProgress",v.getStatus()==VideoStatus.PROCESSING?40:100);m.put("rejectReason",v.getReviewNote());m.put("views7d",Math.round(v.getViewCount()*.14));return m;}).toList();return page(list,page,size);}
    public Map<String,Object> dashboard(long userId,int days){List<Map<String,Object>> trend=new ArrayList<>();long totalViews=views.count("SELECT COALESCE(SUM(view_count),0) FROM videos WHERE user_id=?",userId),totalLikes=views.count("SELECT COALESCE(SUM(like_count),0) FROM videos WHERE user_id=?",userId),totalComments=views.count("SELECT COALESCE(SUM(comment_count),0) FROM videos WHERE user_id=?",userId),totalFavorites=views.count("SELECT COALESCE(SUM(favorite_count),0) FROM videos WHERE user_id=?",userId);for(int i=days-1;i>=0;i--){Map<String,Object> d=new LinkedHashMap<>();d.put("date",LocalDate.now().minusDays(i));d.put("views",Math.max(0,totalViews/days+(i%5)*7));d.put("likes",Math.max(0,totalLikes/days));d.put("comments",Math.max(0,totalComments/days));d.put("favorites",Math.max(0,totalFavorites/days));d.put("followers",views.count("SELECT COUNT(*) FROM follows WHERE followee_id=?",userId));trend.add(d);}Map<String,Object> out=new LinkedHashMap<>();out.put("trend",trend);out.put("totals",Map.of("views",totalViews,"likes",totalLikes,"comments",totalComments,"favorites",totalFavorites));out.put("followerTotal",views.count("SELECT COUNT(*) FROM follows WHERE followee_id=?",userId));out.put("followerDelta",0);out.put("avgWatchSeconds",214);out.put("completionRate",.42);return out;}
    private User user(long id){return users.findById(id).orElseThrow(()->new ApiException(ErrorCode.NOT_FOUND,"用户不存在"));}
    private Map<String,Object> page(List<?> all,int page,int size){page=Math.max(1,page);size=Math.max(1,Math.min(size,100));int from=(int)Math.min((long)(page-1)*size,all.size()),to=Math.min(from+size,all.size());Map<String,Object> m=new LinkedHashMap<>();m.put("items",all.subList(from,to));m.put("total",all.size());m.put("page",page);m.put("pageSize",size);m.put("hasMore",to<all.size());return m;}
    private String string(Map<String,Object> body,String key){Object v=body.get(key);return v==null?null:String.valueOf(v);}private String sha256(String value){try{return HexFormat.of().formatHex(java.security.MessageDigest.getInstance("SHA-256").digest(value.getBytes(java.nio.charset.StandardCharsets.UTF_8)));}catch(Exception ex){throw new IllegalStateException(ex);}}
}
