package com.videoshare.user;

import com.videoshare.auth.CurrentUser;import com.videoshare.common.*;import java.util.*;import org.springframework.security.core.annotation.AuthenticationPrincipal;import org.springframework.web.bind.annotation.*;

@RestController @RequestMapping("/api/v1")
public class UserController {
    private final UserApiService service;private final org.springframework.jdbc.core.JdbcTemplate jdbc;private final IdempotencyService idempotency;
    public UserController(UserApiService service,org.springframework.jdbc.core.JdbcTemplate jdbc,IdempotencyService idempotency){this.service=service;this.jdbc=jdbc;this.idempotency=idempotency;}
    @GetMapping("/categories")public ApiResponse<List<Map<String,Object>>> categories(){return ApiResponse.ok(jdbc.query("SELECT id,name,slug,sort_order FROM categories WHERE status='ACTIVE' ORDER BY sort_order",(rs,n)->Map.of("id",rs.getLong(1),"name",rs.getString(2),"slug",rs.getString(3),"sortOrder",rs.getInt(4))));}
    @GetMapping("/users/me")public ApiResponse<Map<String,Object>> me(@AuthenticationPrincipal CurrentUser c){return ApiResponse.ok(service.profile(require(c),c));}
    @PutMapping("/users/me")public ApiResponse<Map<String,Object>> update(@AuthenticationPrincipal CurrentUser c,@RequestBody Map<String,Object>b){return ApiResponse.ok(service.update(require(c),b));}
    @PutMapping("/users/me/password")public ApiResponse<Map<String,Boolean>> password(@AuthenticationPrincipal CurrentUser c,@RequestBody Map<String,String>b){service.password(require(c),b.get("oldPassword"),b.get("newPassword"));return ApiResponse.ok(Map.of("success",true));}
    @PostMapping("/users/me/real-name")public ApiResponse<Map<String,Object>> realName(@AuthenticationPrincipal CurrentUser c,@RequestHeader(name="Idempotency-Key",required=false)String key,@RequestBody Map<String,String>b){long user=require(c);return ApiResponse.ok(idempotency.execute(user,"user:real-name",key,()->Map.of("status",service.realName(user,b.get("realName"),b.get("idCard")))));}
    @PostMapping("/users/me/deactivate")public ApiResponse<Map<String,Object>> deactivate(@AuthenticationPrincipal CurrentUser c,@RequestHeader(name="Idempotency-Key",required=false)String key,@RequestBody(required=false)Map<String,String>b){long user=require(c);return ApiResponse.ok(idempotency.execute(user,"user:deactivate",key,()->service.deactivate(user,b==null?null:b.get("reason"))));}
    @GetMapping("/users/suggested")public ApiResponse<List<Map<String,Object>>> suggested(@AuthenticationPrincipal CurrentUser c){return ApiResponse.ok(service.suggested(c==null?null:c.id()));}
    @GetMapping("/users/{id}")public ApiResponse<Map<String,Object>> profile(@PathVariable long id,@AuthenticationPrincipal CurrentUser c){return ApiResponse.ok(service.profile(id,c));}
    @GetMapping("/users/{id}/videos")public ApiResponse<Map<String,Object>> videos(@PathVariable long id,@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="12")int pageSize,@AuthenticationPrincipal CurrentUser c){return ApiResponse.ok(service.videos(id,page,pageSize,c==null?null:c.id()));}
    @GetMapping("/users/{id}/favorites")public ApiResponse<Map<String,Object>> favorites(@PathVariable long id,@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="12")int pageSize,@AuthenticationPrincipal CurrentUser c){return ApiResponse.ok(service.favorites(id,page,pageSize,c==null?null:c.id()));}
    @GetMapping("/users/{id}/followers")public ApiResponse<Map<String,Object>> followers(@PathVariable long id,@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="20")int pageSize,@AuthenticationPrincipal CurrentUser c){return ApiResponse.ok(service.follows(id,true,page,pageSize,c==null?null:c.id()));}
    @GetMapping("/users/{id}/following")public ApiResponse<Map<String,Object>> following(@PathVariable long id,@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="20")int pageSize,@AuthenticationPrincipal CurrentUser c){return ApiResponse.ok(service.follows(id,false,page,pageSize,c==null?null:c.id()));}
    @PostMapping("/users/{id}/follow")public ApiResponse<Map<String,Object>> follow(@PathVariable long id,@AuthenticationPrincipal CurrentUser c,@RequestBody Map<String,String>b){return ApiResponse.ok(service.follow(require(c),id,!"UNFOLLOW".equals(b.get("action"))));}
    @GetMapping("/creator/videos")public ApiResponse<Map<String,Object>> creatorVideos(@AuthenticationPrincipal CurrentUser c,@RequestParam(required=false)String status,@RequestParam(defaultValue="1")int page,@RequestParam(defaultValue="10")int pageSize){return ApiResponse.ok(service.creatorVideos(require(c),status,page,pageSize));}
    @GetMapping("/creator/dashboard")public ApiResponse<Map<String,Object>> dashboard(@AuthenticationPrincipal CurrentUser c,@RequestParam(defaultValue="30")int days){return ApiResponse.ok(service.dashboard(require(c),Math.max(1,Math.min(days,90))));}
    private long require(CurrentUser c){if(c==null)throw new ApiException(ErrorCode.UNAUTHORIZED,"请先登录");return c.id();}
}
